export type Producto = {
  slug: string;
  nombre: string;
  categoria: string;
  tiendas: string[];
  img: string;
};

export const PRODUCTOS: Producto[] = [
  { slug: "alpro-coconut-natural", nombre: "Alpro Coconut Natural", categoria: "Vegetales de coco", tiendas: ["Carrefour","Mercadona","Consum","Alcampo","Eroski","Ahorramás","El Corte Inglés / Supercor","Gadis","BM Supermercados"], img: "/productos/alpro-coconut-natural.webp" },
  { slug: "abbot-kinneys-coco-greek", nombre: "Abbot Kinney's Coco Greek Style", categoria: "Vegetales de coco", tiendas: ["Carrefour","Alcampo","Eroski"], img: "/productos/abbot-kinneys-coco-greek.webp" },
  { slug: "moser-roth-90", nombre: "Chocolate negro 90% cacao (Moser Roth)", categoria: "Chocolates", tiendas: ["Aldi"], img: "/productos/moser-roth-90.webp" },
  { slug: "moser-roth-85", nombre: "Chocolate negro 85% cacao (Moser Roth)", categoria: "Chocolates", tiendas: ["Aldi"], img: "/productos/moser-roth-85.webp" },
  { slug: "hacendado-negro-85", nombre: "Chocolate negro 85% (Hacendado)", categoria: "Chocolates", tiendas: ["Mercadona"], img: "/productos/hacendado-negro-85.webp" },
  { slug: "yogur-ecologico-oveja", nombre: "Yogur ecológico de oveja (Cantero de Letur)", categoria: "Yogur de cabra y oveja", tiendas: ["Carrefour","Alcampo","Eroski","Ahorramás","El Corte Inglés / Supercor","Herbolario Navarro","Naturitas"], img: "/productos/yogur-ecologico-oveja.webp" },
  { slug: "yogur-ecologico-cabra", nombre: "Yogur ecológico de cabra (Cantero de Letur)", categoria: "Yogur de cabra y oveja", tiendas: ["Carrefour","Consum","Alcampo","Eroski","Ahorramás","El Corte Inglés / Supercor","Gadis","BM Supermercados","Veritas","Bonpreu","Herbolario Navarro","Naturitas"], img: "/productos/yogur-ecologico-cabra.webp" },
  { slug: "crema-almendra-natruly", nombre: "Crema de almendra (Natruly)", categoria: "Crema de almendra y avellana", tiendas: ["Carrefour","Naturitas","Veritas"], img: "/productos/crema-almendra-natruly.webp" },
  { slug: "crema-almendra-100-carrefour", nombre: "Crema de almendra 100% (Carrefour)", categoria: "Crema de almendra y avellana", tiendas: ["Carrefour"], img: "/productos/crema-almendra-100-carrefour.webp" },
  { slug: "crema-almendra-aldi", nombre: "Crema de almendra alto contenido en fibra (Aldi)", categoria: "Crema de almendra y avellana", tiendas: ["Aldi"], img: "/productos/crema-almendra-aldi.webp" },
  { slug: "crema-avellana-natruly", nombre: "Crema de avellana artesanal (Natruly)", categoria: "Crema de almendra y avellana", tiendas: ["Carrefour","Naturitas"], img: "/productos/crema-avellana-natruly.webp" },
  { slug: "crema-avellana-cacao-natruly", nombre: "Crema de avellana y cacao (Natruly)", categoria: "Crema de almendra y avellana", tiendas: ["Bonpreu","El Corte Inglés / Supercor","Herbolario Navarro"], img: "/productos/crema-avellana-cacao-natruly.webp" },
  { slug: "crema-avellana-100-carrefour", nombre: "Crema de avellana 100% (Carrefour)", categoria: "Crema de almendra y avellana", tiendas: ["Carrefour"], img: "/productos/crema-avellana-100-carrefour.webp" },
  { slug: "crema-avellana-aldi", nombre: "Crema de avellana alto contenido en fibra (Aldi)", categoria: "Crema de almendra y avellana", tiendas: ["Aldi"], img: "/productos/crema-avellana-aldi.webp" },
  { slug: "granola-arandanos-macadamia", nombre: "Granola arándanos y cardamomo (Natruly)", categoria: "Granola", tiendas: ["Carrefour","Naturitas"], img: "/productos/granola-arandanos-macadamia.webp" },
  { slug: "granola-frutos-rojos", nombre: "Granola moras y pasas (Natruly)", categoria: "Granola", tiendas: ["Carrefour","Naturitas"], img: "/productos/granola-frutos-rojos.webp" },
  { slug: "semillas-chia-hacendado", nombre: "Semillas de chía (Hacendado)", categoria: "Semillas", tiendas: ["Mercadona"], img: "/productos/semillas-chia-hacendado.webp" },
  { slug: "chia-carrefour", nombre: "Semillas de chía ecológicas (Carrefour Bio)", categoria: "Semillas", tiendas: ["Carrefour"], img: "/productos/chia-carrefour.webp" },
  { slug: "chia-naturcesta-consum", nombre: "Semillas de chía (Naturcesta)", categoria: "Semillas", tiendas: ["Consum"], img: "/productos/chia-naturcesta-consum.webp" },
  { slug: "chia-eroski-bio", nombre: "Semillas de chía ecológicas (Eroski Bio)", categoria: "Semillas", tiendas: ["Eroski"], img: "/productos/chia-eroski-bio.webp" },
  { slug: "chia-naturitas", nombre: "Semillas de chía Bio (Naturitas Essentials)", categoria: "Semillas", tiendas: ["Naturitas"], img: "/productos/chia-naturitas.webp" },
  { slug: "chia-biogra", nombre: "Semillas de chía ecológicas (Biográ)", categoria: "Semillas", tiendas: ["El Corte Inglés / Supercor","Alcampo"], img: "/productos/chia-biogra.webp" },
  { slug: "chia-bonpreu", nombre: "Semillas de chía ecológicas (Bonpreu)", categoria: "Semillas", tiendas: ["Bonpreu"], img: "/productos/chia-bonpreu.webp" },
  { slug: "avena-esgir", nombre: "Copos de avena sin gluten (Esgir)", categoria: "Avena sin gluten", tiendas: ["Consum","Eroski","El Corte Inglés / Supercor","Gadis"], img: "/productos/avena-esgir.webp" },
  { slug: "avena-ecocesta", nombre: "Copos finos de avena integral sin gluten (Ecocesta)", categoria: "Avena sin gluten", tiendas: ["Ahorramás","BM Supermercados","Bonpreu"], img: "/productos/avena-ecocesta.webp" },
  { slug: "avena-biocop", nombre: "Copos de avena integral finos sin gluten (Biocop)", categoria: "Avena sin gluten", tiendas: ["Naturitas"], img: "/productos/avena-biocop.webp" },
  { slug: "tostas-sarraceno-santiveri", nombre: "Tostadas crujientes de sarraceno (Santiveri Bio)", categoria: "Trigo sarraceno", tiendas: ["Carrefour","Consum","Naturitas","Herbolario Navarro","Alcampo","Eroski","El Corte Inglés / Supercor","Bonpreu"], img: "/productos/tostas-sarraceno-santiveri.webp" },
  { slug: "tostas-sarraceno-le-pain-des-fleurs", nombre: "Tostadas bio de sarraceno (Le Pain des Fleurs)", categoria: "Trigo sarraceno", tiendas: ["Carrefour","Naturitas","Herbolario Navarro","Bonpreu"], img: "/productos/tostas-sarraceno-le-pain-des-fleurs.webp" },
  { slug: "hogaza-sarraceno", nombre: "Hogaza de sarraceno 100% (Levadura Madre)", categoria: "Trigo sarraceno", tiendas: ["Levadura Madre"], img: "/productos/hogaza-sarraceno.webp" },
  { slug: "pan-integral-sarraceno", nombre: "Pan integral de sarraceno (Rincón del Segura)", categoria: "Trigo sarraceno", tiendas: ["Herbolario Navarro", "Veritas"], img: "/productos/pan-integral-sarraceno.webp" },
  { slug: "copos-trigo-sarraceno", nombre: "Copos de trigo sarraceno", categoria: "Trigo sarraceno", tiendas: ["Naturitas"], img: "/productos/copos-trigo-sarraceno.webp" },
  { slug: "tortitas-trigo-sarraceno", nombre: "Tortitas de trigo sarraceno", categoria: "Trigo sarraceno", tiendas: ["Naturitas"], img: "/productos/tortitas-trigo-sarraceno.webp" },
  { slug: "galletas-sarraceno-natural", nombre: "Galletas de trigo sarraceno", categoria: "Trigo sarraceno", tiendas: ["Naturitas"], img: "/productos/galletas-sarraceno-natural.webp" },
  { slug: "galletas-sarraceno-integral", nombre: "Galletas de trigo sarraceno integral", categoria: "Trigo sarraceno", tiendas: ["Naturitas"], img: "/productos/galletas-sarraceno-integral.webp" },
  { slug: "galletas-natruly-naranja", nombre: "Galletas de cacao y naranja (Natruly, consumo ocasional)", categoria: "Trigo sarraceno", tiendas: ["Naturitas","Herbolario Navarro","Veritas"], img: "/productos/galletas-natruly-naranja.webp" },
  { slug: "galletas-natruly-canela", nombre: "Galletas con canela (Natruly, consumo ocasional)", categoria: "Trigo sarraceno", tiendas: ["Naturitas","Herbolario Navarro","Veritas","Bonpreu"], img: "/productos/galletas-natruly-canela.webp" },
  { slug: "galletas-natruly-cacao", nombre: "Galletas con cacao (Natruly, consumo ocasional)", categoria: "Trigo sarraceno", tiendas: ["Naturitas","Herbolario Navarro","Veritas","Bonpreu"], img: "/productos/galletas-natruly-cacao.webp" },
  { slug: "galletas-sarraceno-coco-cacao-mijo", nombre: "Galletas de trigo sarraceno con coco, cacao y mijo (Naturitas Essentials)", categoria: "Trigo sarraceno", tiendas: ["Naturitas"], img: "/productos/galletas-sarraceno-coco-cacao-mijo.webp" },
  { slug: "trigo-sarraceno-hinchado", nombre: "Trigo sarraceno hinchado (Naturitas Essentials)", categoria: "Trigo sarraceno", tiendas: ["Naturitas"], img: "/productos/trigo-sarraceno-hinchado.webp" },
  { slug: "bebida-trigo-sarraceno-isola", nombre: "Bebida de trigo sarraceno (Isola Bio)", categoria: "Trigo sarraceno", tiendas: ["Naturitas"], img: "/productos/bebida-trigo-sarraceno-isola.webp" },
  { slug: "bebida-almendra-hacendado", nombre: "Bebida de almendra 0% azúcar (Hacendado)", categoria: "Bebidas vegetales", tiendas: ["Mercadona"], img: "/productos/bebida-almendra-hacendado.webp" },
  { slug: "bebida-avellana-arroz-hacendado", nombre: "Bebida de avellana y arroz (Hacendado)", categoria: "Bebidas vegetales", tiendas: ["Mercadona"], img: "/productos/bebida-avellana-arroz-hacendado.webp" },
  { slug: "bebida-arroz-avellanas-yosoy", nombre: "Bebida de arroz y avellanas (Yosoy)", categoria: "Bebidas vegetales", tiendas: ["Carrefour","Consum","Alcampo","Bonpreu"], img: "/productos/bebida-arroz-avellanas-yosoy.webp" },
  { slug: "bebida-coco-alpro", nombre: "Bebida de coco sin azúcar (Alpro)", categoria: "Bebidas vegetales", tiendas: ["Carrefour","Alcampo","Eroski","Dia","Ahorramás","Bonpreu"], img: "/productos/bebida-coco-alpro.webp" },
  { slug: "curcuma-latte-naturitas", nombre: "Cúrcuma latte", categoria: "Cúrcuma latte", tiendas: ["Naturitas"], img: "/productos/curcuma-latte-naturitas.webp" },
  { slug: "curcuma-vainilla-latte", nombre: "Cúrcuma vainilla latte", categoria: "Cúrcuma latte", tiendas: ["Naturitas","Herbolario Navarro"], img: "/productos/curcuma-vainilla-latte.webp" },
  { slug: "macarrones-trigo-sarraceno", nombre: "Macarrones de trigo sarraceno", categoria: "Trigo sarraceno", tiendas: ["Herbolario Navarro","Naturitas"], img: "/productos/macarrones-trigo-sarraceno.webp" },
  { slug: "espirales-trigo-sarraceno", nombre: "Espirales de trigo sarraceno", categoria: "Trigo sarraceno", tiendas: ["Herbolario Navarro"], img: "/productos/espirales-trigo-sarraceno.webp" },
  { slug: "tortillas-sin-gluten-old-el-paso", nombre: "Tortillas sin gluten para fajitas (Old El Paso)", categoria: "Fajitas", tiendas: ["Carrefour","Consum","Alcampo","Eroski","Dia","Ahorramás","El Corte Inglés / Supercor","Gadis","Bonpreu"], img: "/productos/tortillas-sin-gluten-old-el-paso.webp" },
  { slug: "cremas-calabaza", nombre: "Cremas de calabaza", categoria: "Cremas", tiendas: ["Naturitas"], img: "/productos/cremas-calabaza.webp" },
  { slug: "caldo-huesos-jarmino", nombre: "Caldo de huesos (Jarmino: ternera, pollo, concentrado)", categoria: "Caldo de huesos", tiendas: ["Naturitas","Herbolario Navarro"], img: "/productos/caldo-huesos-jarmino.webp" },
  { slug: "tortitas-sarraceno-fajitas", nombre: "Tortitas de trigo sarraceno para fajitas", categoria: "Fajitas", tiendas: ["Naturitas"], img: "/productos/tortitas-sarraceno-fajitas.webp" },
  { slug: "proteina-natruly", nombre: "Proteína vegana en polvo (Natruly: cacao, vainilla, fresa)", categoria: "Proteína en polvo", tiendas: ["Naturitas","Carrefour","Herbolario Navarro","Veritas","Bonpreu"], img: "/productos/proteina-natruly.webp" },
  { slug: "proteina-semillas-calabaza-hsn", nombre: "Proteína de semillas de calabaza (HSN)", categoria: "Proteína en polvo", tiendas: [], img: "/productos/proteina-semillas-calabaza-hsn.webp" },
  { slug: "yogi-tea-detox", nombre: "Yogi Tea Detox", categoria: "Infusiones", tiendas: ["Carrefour","Naturitas","Herbolario Navarro","Alcampo","Eroski","Bonpreu"], img: "/productos/yogi-tea-detox.webp" },
  { slug: "yogi-tea-digestion", nombre: "Yogi Tea Digestión", categoria: "Infusiones", tiendas: ["Carrefour","Naturitas","Herbolario Navarro","Alcampo","Eroski","Bonpreu"], img: "/productos/yogi-tea-digestion.webp" },
  { slug: "yogi-tea-jengibre", nombre: "Yogi Tea Jengibre", categoria: "Infusiones", tiendas: ["Carrefour","Naturitas","Herbolario Navarro","Alcampo","Eroski"], img: "/productos/yogi-tea-jengibre.webp" },
  { slug: "yogi-tea-relax", nombre: "Yogi Tea Relax", categoria: "Infusiones", tiendas: ["Carrefour","Naturitas","Herbolario Navarro","Alcampo","Eroski"], img: "/productos/yogi-tea-relax.webp" },
  { slug: "yogi-tea-rooibos", nombre: "Yogi Tea Rooibos", categoria: "Infusiones", tiendas: ["Carrefour","Naturitas","Herbolario Navarro","Alcampo","Eroski","Bonpreu"], img: "/productos/yogi-tea-rooibos.webp" },
  { slug: "yogi-tea-regaliz", nombre: "Yogi Tea Regaliz", categoria: "Infusiones", tiendas: ["Carrefour","Naturitas","Herbolario Navarro","Alcampo","Eroski"], img: "/productos/yogi-tea-regaliz.webp" },
  { slug: "yogi-tea-energia-matutina", nombre: "Yogi Tea Energía matutina", categoria: "Infusiones", tiendas: ["Carrefour","Naturitas","Herbolario Navarro","Alcampo","Eroski"], img: "/productos/yogi-tea-energia-matutina.webp" },
  { slug: "yogi-tea-curcuma-naranja", nombre: "Yogi Tea Cúrcuma Naranja", categoria: "Infusiones", tiendas: ["Carrefour","Naturitas","Herbolario Navarro","Alcampo","Eroski"], img: "/productos/yogi-tea-curcuma-naranja.webp" },
  { slug: "yogi-tea-ashwagandha", nombre: "Yogi Tea Ashwagandha Equilibrio", categoria: "Infusiones", tiendas: ["Carrefour","Naturitas","Herbolario Navarro","Alcampo","Eroski"], img: "/productos/yogi-tea-ashwagandha.webp" },
];

export const CATEGORIAS_ORDEN = [
  "Trigo sarraceno",
  "Vegetales de coco",
  "Yogur de cabra y oveja",
  "Chocolates",
  "Crema de almendra y avellana",
  "Granola",
  "Semillas",
  "Avena sin gluten",
  "Bebidas vegetales",
  "Cúrcuma latte",
  "Fajitas",
  "Cremas",
  "Caldo de huesos",
  "Proteína en polvo",
  "Infusiones",
];
